# Generated by Django 3.1.2 on 2020-10-12 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('taggit_machinetags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinetaggeditem',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taggit_machinetags_machinetaggeditem_tagged_items', to='contenttypes.contenttype', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='machinetaggeditem',
            name='object_id',
            field=models.IntegerField(db_index=True, verbose_name='object ID'),
        ),
    ]
